## Identitas Diri
Nama : Aditya Herdiansyah Putra  
NIM  : A11.2021.13948

## 1. Menambahkan library
 "numpy" berguna memudahkan kita melakukan perhitungan saintifik seperti matriks, aljabar, statistik, dan sebagainya.    
 "matpotlib.pyplot" berguna untuk memvisualisaikan data melalui grafik atau diagram      
 "pandas" berguna untuk memproses data, mulai pembersihan data, manipulasi data, hingga melakukan analisis data.

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# 2. Import dataset
Memuat dataset dan kemudian menampilkan data tersebut agar bisa diproses

In [2]:
data = pd.read_csv("Flipkart.csv")
x = data.iloc[:, :-1].values
y = data.iloc[:, -1].values

In [3]:
print(x)

[['OPPO' 'A53' 'Moonlight Black' ... '64 GB' 4.5 11990]
 ['OPPO' 'A53' 'Mint Cream' ... '64 GB' 4.5 11990]
 ['OPPO' 'A53' 'Moonlight Black' ... '128 GB' 4.3 13990]
 ...
 ['SAMSUNG' 'M52 5G' 'Icy Blue' ... '128 GB' 4.3 27239]
 ['SAMSUNG' 'M52 5G' 'Slate Black' ... '128 GB' 4.2 22989]
 ['SAMSUNG' 'M52 5G' 'Sky Blue' ... '128 GB' 4.2 20350]]


In [4]:
print(y)

[15990 15990 17990 ... 31489 22989 22595]


# 3. Menampilkan atribut yang memiliki missing values
Menampilkan atribut yang memiliki missing values di dalamnya agar kita dapat mengetahui atribut mana yang perlu kita perbaiki.


In [6]:
data.isnull().sum()

Brand               0
Model               0
Color               0
Memory             43
Storage            39
Rating            144
Selling Price       0
Original Price      0
dtype: int64

# 4. Memperbaiki Missing Value (nan)


# 4.1 Pembersihan Data Non-Numerik
Metode yang saya gunakan untuk memperbaiki missing values pada data non-Numerik tersebut yaitu dengan metode imputasi most frequent atau modus. metode ini akan mengambil data yang muncul paling banyak pada dataset. Jika diilustrasikan, terdapat 3 buah data X,Y,Z dan jika yang paling banyak muncul adalah data Z maka data Z yang akan diimputasikan pada Missing Values.

Langkah pertama yaitu kita harus mencari most_frequent data dari atribut yang memiliki missing values

In [16]:
most_frequent_Memory = data["Memory"].mode()[0]

In [17]:
print (most_frequent_Memory)

4 GB


In [18]:
most_frequent_Storage = data["Storage"].mode()[0]

In [19]:
print (most_frequent_Storage)

64 GB


Langkah Kedua, imputasikan data yang dihasilkan dari langkah pertama

In [24]:
data["Memory"] = data["Memory"].fillna(most_frequent_Memory)

In [25]:
data.isnull().sum()

Brand               0
Model               0
Color               0
Memory              0
Storage            39
Rating            144
Selling Price       0
Original Price      0
dtype: int64

In [26]:
data["Storage"] = data["Storage"].fillna(most_frequent_Storage)

In [27]:
data.isnull().sum()

Brand               0
Model               0
Color               0
Memory              0
Storage             0
Rating            144
Selling Price       0
Original Price      0
dtype: int64

# 4.2 Pembersihan Data Numerik
Proses pembersihan data  pada data yang bersifat numerik, saya menggunakan metode imputasi dengan mean. Metode ini akan mengambil data dari rata-rata(mean) dari data pada atribut yang memiliki missing values yang mana nantinya akan diimputasikan pada data yang kosong pada atribut tersebut.    
Data Numerik yang memiliki missing values pada dataset tersebut yaitu pada atribut Rating.


In [32]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(strategy='mean')
data['Rating'] = imputer.fit_transform(data[['Rating']])

In [33]:
print (data)

        Brand   Model            Color Memory Storage  Rating  Selling Price  \
0        OPPO     A53  Moonlight Black   4 GB   64 GB     4.5          11990   
1        OPPO     A53       Mint Cream   4 GB   64 GB     4.5          11990   
2        OPPO     A53  Moonlight Black   6 GB  128 GB     4.3          13990   
3        OPPO     A53       Mint Cream   6 GB  128 GB     4.3          13990   
4        OPPO     A53   Electric Black   4 GB   64 GB     4.5          11990   
...       ...     ...              ...    ...     ...     ...            ...   
3109  SAMSUNG  M52 5G    Blazing Black   6 GB  128 GB     4.3          25990   
3110  SAMSUNG  M52 5G         Icy Blue   6 GB  128 GB     4.3          25489   
3111  SAMSUNG  M52 5G         Icy Blue   8 GB  128 GB     4.3          27239   
3112  SAMSUNG  M52 5G      Slate Black   8 GB  128 GB     4.2          22989   
3113  SAMSUNG  M52 5G         Sky Blue   8 GB  128 GB     4.2          20350   

      Original Price  
0              1

In [34]:
data.isnull().sum()

Brand             0
Model             0
Color             0
Memory            0
Storage           0
Rating            0
Selling Price     0
Original Price    0
dtype: int64

# 5. Encoding data kategori (Atribut)
Proses encoding berguna untuk mengubah nilai kategori atau string menjadi nilai numerik agar dapat digunakan dalam analisis data atau model machine learning. 

Pada kasus ini saya menggunakan teknik encoding One-Hot-Encoding yang mana berjalan dengan membuat variabel dummy baru untuk setiap nilai kategori unik dan mengisinya dengan 0 atau 1.

In [35]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(),[0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [36]:
print(x)

[[0.0 0.0 0.0 ... '64 GB' 4.5 11990]
 [0.0 0.0 0.0 ... '64 GB' 4.5 11990]
 [0.0 0.0 0.0 ... '128 GB' 4.3 13990]
 ...
 [0.0 0.0 0.0 ... '128 GB' 4.3 27239]
 [0.0 0.0 0.0 ... '128 GB' 4.2 22989]
 [0.0 0.0 0.0 ... '128 GB' 4.2 20350]]


# 6. Encoding data kategori (Class / Label) 
Pada bagian ini saya menggunakan teknik encoding LabelEncoder yang mana merupakan salah satu class yang dimiliki oleh library sklearn.preprocessing

In [37]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [38]:
print (y)

[433 433 474 ... 623 547 544]


# 7. Membagi dataset ke dalam training set dan test set

In [39]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 1)

In [40]:
print(x_train)

[[0.0 0.0 0.0 ... '64 GB' 4.4 19990]
 [0.0 0.0 0.0 ... '32 GB' 4.4 7199]
 [0.0 0.0 0.0 ... '64 GB' 4.4 32990]
 ...
 [0.0 0.0 0.0 ... '64 GB' 4.3 18599]
 [0.0 0.0 0.0 ... '64 GB' 4.3 18990]
 [0.0 0.0 0.0 ... '16 GB' 4.1 7139]]


In [41]:
print(x_test)

[[0.0 0.0 0.0 ... '64 GB' 4.5 9999]
 [0.0 0.0 0.0 ... '32 GB' 4.2 8299]
 [0.0 0.0 0.0 ... '32 GB' 4.4 14995]
 ...
 [0.0 0.0 0.0 ... '128 GB' 4.6 53990]
 [0.0 0.0 0.0 ... '16 GB' 4.3 8990]
 [0.0 0.0 0.0 ... '8 GB' 3.9 7999]]


# 8. Feature Scaling

In [79]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
scaled_x_train = sc.fit_transform(x_train[:, :6])
scaled_x_test = sc.transform(x_test[:, :6])

In [80]:
print (scaled_x_train)

[[-0.20236793 -0.37770432 -0.20873269 -0.09653645 -0.13716379 -0.04484711]
 [-0.20236793 -0.37770432 -0.20873269 -0.09653645 -0.13716379 -0.04484711]
 [-0.20236793 -0.37770432 -0.20873269 -0.09653645 -0.13716379 -0.04484711]
 ...
 [-0.20236793 -0.37770432 -0.20873269 -0.09653645 -0.13716379 -0.04484711]
 [-0.20236793 -0.37770432 -0.20873269 -0.09653645 -0.13716379 -0.04484711]
 [-0.20236793 -0.37770432 -0.20873269 -0.09653645 -0.13716379 -0.04484711]]


In [81]:
print (scaled_x_test)

[[-0.20236793 -0.37770432 -0.20873269 -0.09653645 -0.13716379 -0.04484711]
 [-0.20236793 -0.37770432 -0.20873269 -0.09653645 -0.13716379 -0.04484711]
 [-0.20236793 -0.37770432 -0.20873269 -0.09653645 -0.13716379 -0.04484711]
 ...
 [-0.20236793 -0.37770432 -0.20873269 -0.09653645  7.29055375 -0.04484711]
 [-0.20236793 -0.37770432 -0.20873269 -0.09653645 -0.13716379 -0.04484711]
 [-0.20236793 -0.37770432 -0.20873269 -0.09653645  7.29055375 -0.04484711]]
